# Generated by Django 4.2.6 on 2023-10-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
