# Generated by Django 4.2.6 on 2023-10-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tarea_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
